# -*- coding: utf-8 -*-
"""pandasDsaic

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fhP0S78EPjdwR85OPmFCzNnOxwhz2h60
"""

import pandas as pd

df=pd.read_csv ("/content/IRIS.csv")

"""# New Section"""

df.head(10)

df.info()

df.describe()

df.duplicated().sum()







#mean_value=fd("columns")

dt=df.drop_duplicates()

df.isna().sum()

df["species"].value_counts()

df.tail(10)

df.duplicated().sum()